[Java] Test replay of padding g.t. maxMessageLength.
This commit adds a (disabled) test that reproduces an issue we saw in a
testing environment where a replay fails.

Overview of the issue:

- A message "fits" into the current term before fragmentation:
`termOffset + maxMessageLength < termLength`
- but the message does not fit after fragmentation:
`termOffset + requiredLength > termLength`
- ExclusivePublication writes padding where `paddingLength > maxMessageLength`
- ReplaySession fails to recreate due to checks in `appendPadding`
- Fails with the following error:

```
31 observations from 2023-02-28 11:06:24.702+0000 to 2023-02-28 11:06:24.746+0000 for:
java.lang.IllegalArgumentException: message exceeds maxMessageLength of 32768, length=33472
	at io.aeron.Publication.checkMaxMessageLength(Publication.java:675)
	at io.aeron.ExclusivePublication.appendPadding(ExclusivePublication.java:438)
	at io.aeron.archive.ReplaySession.replay(ReplaySession.java:452)
	at io.aeron.archive.ReplaySession.doWork(ReplaySession.java:229)
	at io.aeron.archive.SessionWorker.doWork(SessionWorker.java:64)
	at io.aeron.archive.ArchiveConductor$Replayer.doWork(ArchiveConductor.java:2195)
	at org.agrona.concurrent.AgentInvoker.invoke(AgentInvoker.java:147)
	at io.aeron.archive.SharedModeArchiveConductor.doWork(SharedModeArchiveConductor.java:56)
	at org.agrona.concurrent.AgentRunner.doWork(AgentRunner.java:304)
	at org.agrona.concurrent.AgentRunner.workLoop(AgentRunner.java:296)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:829)

1 distinct errors observed.
```