[C] Cubic congestion control (#1065)
* [C] Add test for `cc` URI parameter.

* [C] Add `aeron_congestion_control_default_strategy_supplier` as an indirection layer.

* [C] Read `cc` parameter and determine which congestion control should be applied.

* [C] Add congestion_control_test.

* [C] Fix compilation error: unknown type name 'size_t'.

* [C] Fix Cubic ENV var names.

* [C] Add basic Cubic impl skeleton.

* [C] Add aeron_congestion_control_strategy_on_rttm_sent_func_t.

* [C] Fail on invalid initial_rtt ENV value.

* [C] Implement the rest of Cubic functionality.

* [C] Add cubic config test.

* [C] Use `strncmp` instead of `strcmp`.

* [C] Add `aeron_un/setenv` functions so it works on Windows.

* [C] Do not compare function pointers to make MSVC happy.

* Revert "[C] Add `aeron_un/setenv` functions so it works on Windows."

This reverts commit aeadf86a

* [C] Use `aeron_env_set`/`aeron_env_unset` functions.

* [C] Fix string comparison.

* [C] Fix compalation error.

* [C] Remove negation from define.